name: Trigger webhook in other repo
on:
  - issue_comment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Workflow trigger
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        AUTH: ${{ secrets.WEBHOOK_AUTH }}
      run:
        curl -X POST $WEBHOOK_URL --user $AUTH --data "{\"event_type\":\"i_did_something\"}"
