name: Trigger webhook in other repo
on:
  - issue_comment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Workflow trigger
      run:
        gh workflow run --repo eiriksm/eiriksm.dev deploy.yml
